### ISSUE TITLE
Remove Android SDK Build Tools version (27.0.3)

### ISSUE THREAD

**Issue by mTwTm** [mozilla-mobile/android-permission-handler#8]
Per what I know we can now skip that declaration and the latest is always used if preferred.

**Comment by kartikgits** [comment]
@mTwTm I'm a beginner and would like to work on it if not already taken.

**Comment by mTwTm** [comment]
Yes, please take it! I'm expecting this ticket to be simply removing that buildToolsVersion line.

**Comment by mTwTm** [comment]
Fixed in #9
